<a href="https://colab.research.google.com/github/Prezzo-K/Food-Vision-Mini/blob/main/Exercise_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

In [1]:
# import torch
import torch

torch.__version__

'2.5.1+cu124'

Create a random tensor with shape (7, 7).

In [2]:
random_tensor = torch.rand(size = (7, 7))
random_tensor

tensor([[0.2498, 0.5665, 0.0111, 0.7020, 0.2586, 0.9197, 0.4162],
        [0.8078, 0.5821, 0.7295, 0.6849, 0.1043, 0.4426, 0.8953],
        [0.6801, 0.7720, 0.8665, 0.4354, 0.6101, 0.4495, 0.8156],
        [0.1450, 0.3263, 0.6352, 0.8477, 0.2994, 0.6920, 0.7191],
        [0.9767, 0.1375, 0.4284, 0.8058, 0.7072, 0.6193, 0.4396],
        [0.8405, 0.6677, 0.4398, 0.6636, 0.8359, 0.9056, 0.9181],
        [0.7080, 0.8556, 0.5804, 0.6710, 0.8114, 0.9000, 0.0332]])

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
another_ranodm_tensor = torch.rand(size = (1,7))
torch.matmul(random_tensor, another_ranodm_tensor.T) # (7 x 7) x (7 x 1) = 7 x 1

tensor([[1.6543],
        [2.6733],
        [2.5607],
        [2.1483],
        [2.4859],
        [2.8767],
        [2.2706]])

Set the random seed to 0 and do exercises 2 & 3 over again.

In [4]:
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)

X = torch.rand(size = (7, 7))
print(X)
Y = torch.rand(size = (1, 7))
print(Y)
torch.matmul(X, Y.T)

tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]])
tensor([[0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149, 0.3993]])


tensor([[1.5166],
        [3.1874],
        [2.5350],
        [2.8343],
        [2.6844],
        [2.6483],
        [2.4059]])

Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [18]:
device = "cuda" if torch.cuda.is_available else "cpu"

torch.manual_seed(1234)

first_tensor = torch.rand(size = (2, 3)).to(device)
second_tensor = torch.rand(size = (2, 3)).to(device)

first_tensor, second_tensor

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [24]:
first_tensor.shape, second_tensor.shape

out = torch.matmul(first_tensor, second_tensor.T)
out

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

Find the maximum and minimum values of the output of 7.

In [31]:
out.max(), out.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

Find the maximum and minimum index values of the output of 7.

In [34]:
out.argmax(dim = 0), out.argmin(dim = 1)

(tensor([1, 1], device='cuda:0'), tensor([0, 0], device='cuda:0'))

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [40]:
random_T = torch.rand(size = (1, 1, 1, 10))
print(random_T)

new_T = random_T.squeeze()
print(new_T)

torch.manual_seed(7)

random_T.shape, new_T.shape

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


(torch.Size([1, 1, 1, 10]), torch.Size([10]))